apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: firefly-iii
spec:
  interval: 5m
  chart:
    spec:
      chart: firefly-iii-stack
      version: ">=0.9.0"
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: firefly-iii
  values:
    # Enable Firefly III components
    firefly-iii:
      enabled: true
      replicaCount: 1
      
      # Use NodePort to expose on server IP
      service:
        type: NodePort
        port: 80
        nodePort: 30080  # Access via http://10.0.0.3:30080
      
      # Disable ingress since no Traefik
      ingress:
        enabled: false
      
      # Database configuration
      config:
        env:
          DB_CONNECTION: pgsql
          DB_HOST: firefly-iii-firefly-db
          DB_PORT: "5432"
          DB_DATABASE: firefly
          DB_USERNAME: firefly
          DEFAULT_LANGUAGE: en_US
          DEFAULT_LOCALE: equal
          TRUSTED_PROXIES: "**"
          TZ: UTC
      
      # Persistent storage for uploads
      persistence:
        enabled: true
        accessModes: ReadWriteOnce
        storage: 5Gi
      
      # Enable cronjob for recurring tasks
      cronjob:
        enabled: true
        schedule: "0 3 * * *"
        auth:
          existingSecret: firefly-iii-secrets
          secretKey: token
    
    # PostgreSQL database configuration
    firefly-db:
      enabled: true
      
      configs:
        DBNAME: firefly
        DBUSER: firefly
        POSTGRES_USER: firefly
        POSTGRES_PASSWORD: "firefly-change-me"  # CHANGE THIS!
        TZ: UTC
      
      storage:
        accessModes: ReadWriteOnce
        dataSize: 5Gi
    
    # Data importer (optional - set to false if not needed)
    importer:
      enabled: true
      
      service:
        type: NodePort
        port: 80
        nodePort: 30081  # Access via http://10.0.0.3:30081
      
      # Disable ingress since no Traefik
      ingress:
        enabled: false
      
      fireflyiii:
        url: "http://firefly-iii.firefly-iii.svc.cluster.local"
        vanityUrl: "http://10.0.0.3:30080"
      
      config:
        env:
          TZ: UTC
          IGNORE_DUPLICATE_ERRORS: "false"
          FIREFLY_III_URL: "http://firefly-iii.firefly-iii.svc.cluster.local"
          VANITY_URL: "http://10.0.0.3:30080"
        envValueFrom:
          FIREFLY_III_ACCESS_TOKEN:
            secretKeyRef:
              name: firefly-iii-secrets
              key: accessToken
