apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: firefly-iii
spec:
  interval: 5m
  chart:
    spec:
      chart: firefly-iii-stack
      version: ">=0.9.0"
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: firefly-iii
  values:
    # Enable Firefly III components
    firefly-iii:
      enabled: true
      replicaCount: 1
      
      # Configure service as LoadBalancer for local network access
      service:
        type: LoadBalancer
        port: 80
      
      # Database configuration
      config:
        env:
          DB_CONNECTION: pgsql
          DB_HOST: firefly-iii-firefly-db
          DB_PORT: "5432"
          DB_DATABASE: firefly
          DB_USERNAME: firefly
          DEFAULT_LANGUAGE: en_US
          DEFAULT_LOCALE: equal
          TRUSTED_PROXIES: "**"
          TZ: UTC
      
      # Persistent storage for uploads
      persistence:
        enabled: true
        accessModes: ReadWriteOnce
        storage: 5Gi
      
      # Enable cronjob for recurring tasks
      cronjob:
        enabled: true
        schedule: "0 3 * * *"
        auth:
          token: ""  # You should set this to a random token
    
    # PostgreSQL database configuration
    firefly-db:
      enabled: true
      
      configs:
        DBNAME: firefly
        DBUSER: firefly
        POSTGRES_USER: firefly
        POSTGRES_PASSWORD: "firefly-change-me"  # CHANGE THIS!
        TZ: UTC
      
      storage:
        accessModes: ReadWriteOnce
        dataSize: 5Gi
    
    # Data importer (optional - set to false if not needed)
    importer:
      enabled: true
      
      service:
        type: LoadBalancer
        port: 80
      
      fireflyiii:
        url: "http://firefly-iii-firefly-iii:80"
        auth:
          accessToken: ""  # You need to generate this from Firefly III web UI
      
      config:
        env:
          TZ: UTC
          IGNORE_DUPLICATE_ERRORS: "false"
